// ข้อมูลตำแหน่งงานทั้งหมด ใช้ร่วมกันระหว่างหน้า Home (การ์ดแนะนำ) และหน้า JobDetail (รายละเอียดงาน)
// เพิ่ม/แก้ไขงานได้ที่ไฟล์นี้ที่เดียว ไม่ต้องไปแก้หลายจุด

export const jobs = [
  {
    id: 1,
    title: "Web Designer",
    company: "Amazon",
    logoLetter: "A",
    logoClass: "green-logo",
    location: "Seattle, WA",
    workMode: "Remote/Office",
    type: "Full time",
    level: "Senior",
    salary: "$127k/yr",
    applicants: "60+ applicants",
    match: 79,
    matchBadgeClass: "blue-badge",
    postedAgo: "3 hours ago",
    teamSize: "9 designers",
    visaSponsorship: "Available",
    matchBreakdown: [
      { label: "Visual design", percent: 82 },
      { label: "Figma", percent: 90 },
      { label: "Storytelling", percent: 68 },
    ],
    aboutRole:
      "ออกแบบภาษาภาพให้เครื่องมือฝั่งผู้ขายของ Amazon ทำงานใกล้ชิดกับ PM ที่พูดกันด้วยตัวย่อล้วนๆ ทั้งวัน",
    responsibilities: [
      "ออกแบบแดชบอร์ดให้สเปรดชีตดูเป็นมิตรขึ้นมาหน่อย",
      "ทำ prototype ใน Figma ให้เสร็จก่อนวิศวกรจะตื่นมาทำงาน",
      "ปกป้องค่า padding 4px ของตัวเองในที่ประชุม design review รายสัปดาห์",
    ],
    requirements: [
      "ประสบการณ์ออกแบบ UI ที่ขึ้น production จริง 4 ปีขึ้นไป",
      "พอร์ตที่ไม่ใช่แอปสั่งอาหารล้วนๆ",
      "ความอดทนรับฟีดแบ็กจาก stakeholder 12 คนพร้อมกัน",
    ],
  },
  {
    id: 2,
    title: "Web Designer",
    company: "BeReal",
    logoLetter: "B",
    logoClass: "indigo-logo",
    location: "Paris, France",
    workMode: "Remote",
    type: "Full time",
    level: "Middle",
    salary: "$115k/yr",
    applicants: "<40 applicants",
    match: 86,
    matchBadgeClass: "green-badge",
    postedAgo: "8 hours ago",
    teamSize: "5 designers",
    visaSponsorship: "Not available",
    matchBreakdown: [
      { label: "Mobile-first design", percent: 88 },
      { label: "Motion design", percent: 79 },
      { label: "Brand consistency", percent: 91 },
    ],
    aboutRole:
      "ดูแลหน้าตาแอปที่เตือนให้คนวางมือถือแล้วถ่ายรูปตัวเองตอนหน้าไม่พร้อมที่สุด ให้ยังดูน่ารักอยู่ดี",
    responsibilities: [
      "ออกแบบ micro-interaction ให้การแจ้งเตือนกวนใจแบบน่ารัก ไม่ใช่แบบน่ารำคาญ",
      "ทดสอบดีไซน์กับผู้ใช้จริงที่มักถ่ายรูปตอนเพิ่งตื่นนอน",
      "รักษาความสม่ำเสมอของแบรนด์ในทุกแพลตฟอร์ม",
    ],
    requirements: [
      "ประสบการณ์ออกแบบแอปมือถือที่คนใช้งานทุกวัน",
      "เข้าใจเรื่อง motion และ micro-interaction",
      "ทำงานข้ามทีมกับวิศวกรในไทม์โซนต่างกันได้",
    ],
  },
  {
    id: 3,
    title: "UX/UI Designer",
    company: "Wise",
    logoLetter: "W",
    logoClass: "orange-logo",
    location: "London, UK",
    workMode: "Remote/Office",
    type: "Full time",
    level: "Senior",
    salary: "$120k/yr",
    applicants: "30+ applicants",
    match: 73,
    matchBadgeClass: "blue-badge",
    postedAgo: "1 day ago",
    teamSize: "12 designers",
    visaSponsorship: "Available",
    matchBreakdown: [
      { label: "Fintech UX", percent: 75 },
      { label: "Accessibility", percent: 70 },
      { label: "Data visualization", percent: 74 },
    ],
    aboutRole:
      "ออกแบบประสบการณ์โอนเงินข้ามประเทศให้รู้สึกเรียบง่าย แม้เบื้องหลังจะซับซ้อนเหมือนเขาวงกต",
    responsibilities: [
      "ลดขั้นตอนการโอนเงินจาก 9 ขั้นตอนให้เหลือ 3 ขั้นตอนแบบไม่มีใครงง",
      "ออกแบบให้ตัวเลขอัตราแลกเปลี่ยนดูน่าเชื่อถือ ไม่ใช่น่ากลัว",
      "ทำงานร่วมกับทีม compliance โดยไม่ทำให้ดีไซน์ดูเป็นแบบฟอร์มราชการ",
    ],
    requirements: [
      "ประสบการณ์ออกแบบผลิตภัณฑ์ fintech หรือ B2C ที่ซับซ้อน",
      "เข้าใจหลัก accessibility ในระดับที่นำไปใช้ได้จริง",
      "สื่อสารเหตุผลการออกแบบกับทีม non-design ได้ชัดเจน",
    ],
  },
  {
    id: 4,
    title: "UX Researcher",
    company: "Notion",
    logoLetter: "N",
    logoClass: "purple-logo",
    location: "San Francisco, CA",
    workMode: "Remote",
    type: "Full time",
    level: "Middle",
    salary: "$98k/yr",
    applicants: "20+ applicants",
    match: 81,
    matchBadgeClass: "green-badge",
    postedAgo: "2 days ago",
    teamSize: "6 researchers",
    visaSponsorship: "Available",
    matchBreakdown: [
      { label: "User interviews", percent: 89 },
      { label: "Synthesis & reporting", percent: 84 },
      { label: "Workspace tools domain", percent: 70 },
    ],
    aboutRole:
      "หาคำตอบว่าทำไมคนถึงสร้าง workspace สวยๆ ไว้ดูเฉยๆ แล้วไม่เคยกลับมาเปิดอีกเลย",
    responsibilities: [
      "สัมภาษณ์ผู้ใช้ที่มีหน้า Notion ว่างเปล่ามาสามเดือนแล้ว",
      "สรุปอินไซต์ให้ทีมโปรดักต์อ่านจบใน 5 นาที ไม่ใช่ 50 หน้า",
      "ออกแบบแบบสำรวจที่คนตอบจริง ไม่ปิดหนีตั้งแต่ข้อ 2",
    ],
    requirements: [
      "ประสบการณ์งานวิจัยผู้ใช้ทั้งเชิงคุณภาพและเชิงปริมาณ",
      "เคยทำงานกับผลิตภัณฑ์ productivity หรือ workspace tools",
      "เล่าเรื่องข้อมูลให้คนไม่ใช่นักวิจัยเข้าใจได้",
    ],
  },
  {
    id: 5,
    title: "UI Engineer",
    company: "Linear",
    logoLetter: "L",
    logoClass: "bright-green-logo",
    location: "New York, NY",
    workMode: "Office",
    type: "Full time",
    level: "Senior",
    salary: "$132k/yr",
    applicants: "45+ applicants",
    match: 68,
    matchBadgeClass: "yellow-badge",
    postedAgo: "5 hours ago",
    teamSize: "8 engineers",
    visaSponsorship: "Not available",
    matchBreakdown: [
      { label: "React & animation", percent: 74 },
      { label: "Design systems", percent: 71 },
      { label: "Performance tuning", percent: 60 },
    ],
    aboutRole:
      "เขียนโค้ด UI ที่ลื่นจนผู้ใช้เริ่มสงสัยว่าซอฟต์แวร์จัดการงานทำไมเร็วกว่าการเปิดโน้ตในมือถือ",
    responsibilities: [
      "ปรับ animation ให้ลื่นระดับ 120fps โดยไม่ทำให้แบตเตอรี่หมดไว",
      "สร้าง component ที่นำกลับมาใช้ได้ทั้งบริษัทโดยไม่มีใครถามว่า 'ใช้ยังไง'",
      "รีวิวโค้ดแบบตรงไปตรงมา (ธรรมเนียมของทีม)",
    ],
    requirements: [
      "ประสบการณ์ React และ CSS ขั้นสูง 4 ปีขึ้นไป",
      "เคยดูแล design system ระดับโปรดักชัน",
      "สนใจเรื่อง performance และ interaction detail",
    ],
  },
  {
    id: 6,
    title: "Brand Designer",
    company: "Figma",
    logoLetter: "F",
    logoClass: "coral-logo",
    location: "Remote (US)",
    workMode: "Remote",
    type: "Contract",
    level: "Middle",
    salary: "$90k/yr",
    applicants: "15+ applicants",
    match: 91,
    matchBadgeClass: "green-badge",
    postedAgo: "12 hours ago",
    teamSize: "4 designers",
    visaSponsorship: "Not available",
    matchBreakdown: [
      { label: "Brand identity", percent: 95 },
      { label: "Illustration", percent: 88 },
      { label: "Social content", percent: 90 },
    ],
    aboutRole:
      "ดูแลหน้าตาแบรนด์ของเครื่องมือที่นักออกแบบทั้งโลกใช้อยู่ โดยห้ามทำให้แบรนด์ดูเหมือน SaaS ทั่วไปเด็ดขาด",
    responsibilities: [
      "ออกแบบภาพประกอบสำหรับแคมเปญที่ต้องดูสนุกแต่ยังดูมืออาชีพ",
      "รักษาความสม่ำเสมอของแบรนด์ข้ามทุกช่องทาง ตั้งแต่เว็บยันสติกเกอร์แจกงานอีเวนต์",
      "ทำงานใกล้ชิดกับทีมการตลาดที่เปลี่ยนใจได้วันละสามรอบ",
    ],
    requirements: [
      "พอร์ตงานแบรนด์ดิ้งที่แสดงความคิดสร้างสรรค์ชัดเจน",
      "ประสบการณ์ทำงานฟรีแลนซ์หรือสัญญาจ้างมาก่อน",
      "สื่อสารและรับฟีดแบ็กได้เร็ว เพราะไทม์ไลน์มักจะกระชั้นชิด",
    ],
  },
];

export function getJobById(id) {
  return jobs.find((job) => String(job.id) === String(id));
}