// ข้อมูลตำแหน่งงานทั้งหมด ปรับให้อิงตาม ai_job_market.csv
export const jobs = [
  {
    id: 1,
    title: "Data Analyst",
    company: "Foster and Sons",
    logoLetter: "F",
    logoClass: "green-logo",
    location: "Tracybury, AR",
    workMode: "Remote/Office",
    type: "Full-time",
    level: "Mid",
    salary: "$101k/yr",
    applicants: "60+ applicants",
    match: 79,
    matchBadgeClass: "blue-badge",
    postedAgo: "3 hours ago",
    teamSize: "9 analysts",
    visaSponsorship: "Available",
    industry: "Healthcare",
    matchBreakdown: [
      { label: "Data visualization", percent: 82 },
      { label: "SQL & Pandas", percent: 90 },
      { label: "Business Insights", percent: 68 },
    ],
    aboutRole:
      "วิเคราะห์ข้อมูลและสร้างรายงานเชิงลึกเพื่อช่วยขับเคลื่อนการตัดสินใจทางธุรกิจในอุตสาหกรรม Healthcare",
    responsibilities: [
      "เขียน SQL query และใช้ Pandas ประมวลผลชุดข้อมูลขนาดใหญ่",
      "สร้าง Dashboard สรุปผลงานให้ทีมบริหารเข้าใจง่าย",
      "ตรวจสอบความถูกต้องของข้อมูลและจัดการ missing values",
    ],
    requirements: [
      "ประสบการณ์ทำงานสาย Data Analyst 2 ปีขึ้นไป",
      "ทักษะการใช้ SQL, Python (Pandas/NumPy) เป็นอย่างดี",
      "สามารถสื่อสารผลลัพธ์เชิงตัวเลขให้ทีมทั่วไปเข้าใจได้",
    ],
  },
  {
    id: 2,
    title: "Computer Vision Engineer",
    company: "Boyd, Myers and Ramirez",
    logoLetter: "B",
    logoClass: "indigo-logo",
    location: "Lake Scott, CU",
    workMode: "Remote",
    type: "Full-time",
    level: "Senior",
    salary: "$111k/yr",
    applicants: "<40 applicants",
    match: 86,
    matchBadgeClass: "green-badge",
    postedAgo: "8 hours ago",
    teamSize: "5 engineers",
    visaSponsorship: "Not available",
    industry: "Tech",
    matchBreakdown: [
      { label: "PyTorch & CUDA", percent: 88 },
      { label: "Image Processing", percent: 79 },
      { label: "Model Optimization", percent: 91 },
    ],
    aboutRole:
      "พัฒนาและปรับแต่งโมเดล Computer Vision สำหรับประมวลผลภาพความละเอียดสูงในระบบสเกลใหญ่",
    responsibilities: [
      "เทรนโมเดลตรวจจับและจำแนกวัตถุด้วย PyTorch และ OpenCV",
      "ปรับแต่งความเร็วในการรันโมเดลผ่าน CUDA",
      "ทดสอบระบบประมวลผลภาพกับชุดข้อมูลจริง",
    ],
    requirements: [
      "ประสบการณ์พัฒนา Computer Vision หรือ Deep Learning 3 ปีขึ้นไป",
      "เชี่ยวชาญการใช้ Python, PyTorch และ Scikit-learn",
      "เข้าใจโครงสร้างระบบประมวลผลภาพแบบเรียลไทม์",
    ],
  },
  {
    id: 3,
    title: "Quant Researcher",
    company: "Wise",
    logoLetter: "W",
    logoClass: "orange-logo",
    location: "London, UK",
    workMode: "Remote/Office",
    type: "Full-time",
    level: "Senior",
    salary: "$120k/yr",
    applicants: "30+ applicants",
    match: 73,
    matchBadgeClass: "blue-badge",
    postedAgo: "1 day ago",
    teamSize: "12 researchers",
    visaSponsorship: "Available",
    industry: "Finance",
    matchBreakdown: [
      { label: "Statistical modeling", percent: 75 },
      { label: "Time series", percent: 70 },
      { label: "Data visualization", percent: 74 },
    ],
    aboutRole:
      "พัฒนาโมเดลเชิงปริมาณและการพยากรณ์อนุกรมเวลาเพื่อวิเคราะห์ความเสี่ยงและโอกาสการลงทุน",
    responsibilities: [
      "สร้างและทดสอบอัลกอริทึมพยากรณ์ตลาดการเงิน",
      "วิเคราะห์ข้อมูลย้อนหลังด้วยเครื่องมือทางสถิติขั้นสูง",
      "ทำงานร่วมกับทีมวิศวกรเพื่อนำโมเดลขึ้นระบบจริง",
    ],
    requirements: [
      "ประสบการณ์วิจัยเชิงปริมาณหรือ Data Science ในสายการเงิน",
      "เชี่ยวชาญการวิเคราะห์ Time Series และสถิติขั้นสูง",
      "เขียนโค้ด Python ได้คล่องแคล่ว",
    ],
  },
  {
    id: 4,
    title: "AI Researcher",
    company: "Notion",
    logoLetter: "N",
    logoClass: "purple-logo",
    location: "San Francisco, CA",
    workMode: "Remote",
    type: "Full-time",
    level: "Mid",
    salary: "$98k/yr",
    applicants: "20+ applicants",
    match: 81,
    matchBadgeClass: "green-badge",
    postedAgo: "2 days ago",
    teamSize: "6 researchers",
    visaSponsorship: "Available",
    industry: "Tech",
    matchBreakdown: [
      { label: "NLP & LLM", percent: 89 },
      { label: "Algorithm Design", percent: 84 },
      { label: "Python & PyTorch", percent: 70 },
    ],
    aboutRole:
      "วิจัยและพัฒนาอัลกอริทึมปัญญาประดิษฐ์รุ่นใหม่เพื่อยกระดับฟีเจอร์อัจฉริยะในเครื่องมือ Workspace",
    responsibilities: [
      "ทดลองโครงสร้างโมเดล LLM และเทคนิค Prompt Engineering",
      "ประเมินประสิทธิภาพและหาแนวทางลดความผิดพลาดของโมเดล",
      "เขียนบทความวิจัยและเอกสารทางเทคนิคภายในทีม",
    ],
    requirements: [
      "ปริญญาตรีหรือโท สาขา Computer Science หรือเทียบเท่า",
      "ประสบการณ์งานวิจัยด้าน AI, Machine Learning หรือ NLP",
      "มีผลงานทดลองหรือโปรเจกต์ที่เกี่ยวข้องกับ Deep Learning",
    ],
  },
  {
    id: 5,
    title: "ML Engineer",
    company: "Linear",
    logoLetter: "L",
    logoClass: "bright-green-logo",
    location: "New York, NY",
    workMode: "Office",
    type: "Full-time",
    level: "Senior",
    salary: "$132k/yr",
    applicants: "45+ applicants",
    match: 68,
    matchBadgeClass: "yellow-badge",
    postedAgo: "5 hours ago",
    teamSize: "8 engineers",
    visaSponsorship: "Not available",
    industry: "Tech",
    matchBreakdown: [
      { label: "MLOps & Pipeline", percent: 74 },
      { label: "Model Deployment", percent: 71 },
      { label: "Performance tuning", percent: 60 },
    ],
    aboutRole:
      "สร้างโครงสร้างพื้นฐานและไปป์ไลน์สำหรับนำโมเดล Machine Learning ไปใช้งานจริงในระบบโปรดักชัน",
    responsibilities: [
      "สร้างระบบ MLOps อัตโนมัติสำหรับการเทรนและประเมินผลโมเดล",
      "ปรับแต่งความเร็วและความเสถียรในการตอบสนองของ API",
      "ร่วมมือกับทีมซอฟต์แวร์ในการเชื่อมต่อระบบ AI",
    ],
    requirements: [
      "ประสบการณ์พัฒนา ML Pipelines และระบบ Production 4 ปีขึ้นไป",
      "เชี่ยวชาญการใช้งาน Docker, Kubernetes และ Cloud Services",
      "มีความเข้าใจเรื่องระบบ Microservices และ API Design",
    ],
  },
  {
    id: 6,
    title: "AI Product Manager",
    company: "Figma",
    logoLetter: "F",
    logoClass: "coral-logo",
    location: "Remote (US)",
    workMode: "Remote",
    type: "Contract",
    level: "Middle",
    salary: "$90k/yr",
    applicants: "15+ applicants",
    match: 91,
    matchBadgeClass: "green-badge",
    postedAgo: "12 hours ago",
    teamSize: "4 designers",
    visaSponsorship: "Not available",
    industry: "E-commerce",
    matchBreakdown: [
      { label: "Product Strategy", percent: 95 },
      { label: "AI Feature Planning", percent: 88 },
      { label: "Cross-functional", percent: 90 },
    ],
    aboutRole:
      "กำหนดทิศทางและแผนงานในการนำเทคโนโลยี AI มาผนวกเข้ากับผลิตภัณฑ์ดิจิทัล",
    responsibilities: [
      "วางแผนฟีเจอร์ AI ตั้งแต่ขั้นตอนวิจัยจนถึงปล่อยสู่ตลาด",
      "ประสานงานระหว่างทีมวิศวกร นักวิจัย และทีมดีไซน์",
      "วิเคราะห์ความต้องการของผู้ใช้งานและตัวชี้วัดความสำเร็จของผลิตภัณฑ์",
    ],
    requirements: [
      "ประสบการณ์บริหารผลิตภัณฑ์ (Product Management) สายเทคโนโลยีหรือ AI",
      "มีความเข้าใจภาพรวมของโมเดล AI และความสามารถของระบบ",
      "ทักษะการสื่อสารและการบริหารโครงการที่ดีเยี่ยม",
    ],
  },
];

export function getJobById(id) {
  return jobs.find((job) => String(job.id) === String(id));
}